### ISSUE TITLE
Opening games is broken outright, negative reviews on GNOME Software page

### ISSUE THREAD

**Issue by superusercode** [flathub/org.gnome.Games#1]

**Comment by Kekun** [comment]
This bug entry is extremely vague, can you please be more specific?

**Comment by superusercode** [comment]
I wasn't aware that the flatpak was missing some features intentionally. Perhaps it would be best to update the Software listing to reflect that?

**Comment by superusercode** [comment]
![image](https://user-images.githubusercontent.com/23001825/36075926-57ada5de-0f23-11e8-96a4-630425a04931.png)
![screenshot from 2018-02-11 12-02-32](https://user-images.githubusercontent.com/23001825/36075943-7ff0f726-0f23-11e8-91fd-c5c1f55f7b48.png)
