### ISSUE TITLE
The app crashes while listing the games at my filesystem

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.Games#23]
The app crashes while listing the games at my filesystem.

I have a lot of games at my system and never used *tracker* to detect them.
I made a test with tracker and the result is a crash:

```
$ org.gnome.Games 
**
GamesPlayStation:ERROR:../plugins/playstation/src/playstation-game-factory.vala:100:games_play_station_game_factory_add_uri_with_error: assertion failed: (!media_for_disc_id.contains (new_disc_id))
Bail out! GamesPlayStation:ERROR:../plugins/playstation/src/playstation-game-factory.vala:100:games_play_station_game_factory_add_uri_with_error: assertion failed: (!media_for_disc_id.contains (new_disc_id))
$
```

**Comment by Exalm** [comment]
First, please open an issue upstream, this is just packaging.

https://gitlab.gnome.org/GNOME/gnome-games/issues

Second, this isn't any games, this is specifically PSX games (the logic for detecting multi-disk games). Please mention what game it is when opening an issue there.

Also please try nightly, it _might_ be fixed there as I changed that code significantly.

**Comment by felipehw** [comment]
I opened a bug there: <https://gitlab.gnome.org/GNOME/gnome-games/-/issues/287>
