### ISSUE TITLE
Add lutris flatpak games?

### ISSUE THREAD

**Issue by nickavem** [flathub/org.gnome.Games#27]
This may be kind of a strange request, but I would like to be able to add games from the lutris flatpak. I prefer the gnome games flatpak interface, and want all my stuff in one place, but also want to be able to run certain wine games easily. Would it be possible to somehow spawn the lutris flatpak from within the sandbox, without and existing d-bus API (as I believe the steam flatpak does it)?

**Comment by Exalm** [comment]
No, and it's not really a goal, sorry.
