### ISSUE TITLE
When both Gnome Games and Steam are installed via Flathub, Gnome Games duplicates installed Steam Games And Lists Proton

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.gnome.Games#6]
All entries from Steam are duplicated and Proton is even listed as a game.

**Comment by Exalm** [comment]
Issues are tracked in https://gitlab.gnome.org/GNOME/gnome-games/issues

In particular, Proton issue is tracked in https://gitlab.gnome.org/GNOME/gnome-games/issues/103

As for the "All entries from Steam are duplicated": what do you mean? Screenshot? Do you have Steam installed both on host and via Flathub with the same games installed in both?

**Comment by Saroufim** [comment]
Now I'm confused. Should I reply here or open a ticket on the proper issue tracker? In any case, I only have steam from flathub and it's just that all Steam games are listed twice.

**Comment by Exalm** [comment]
> I only have steam from flathub and it's just that all Steam games are listed twice.

Ok, then please open an issue on gitlab. :)
